### ISSUE TITLE
ARBOLcentroidTaxonomy returns length(v) error

### ISSUE THREAD

**Issue by leonardjn** [jo-m-lab/ARBOL#3]
When I run `ARBOLcentroidTaxonomy()`, it returns the following error:

> Error in length(v) > 0 && !is.na(v) :
> 'length = 2' in coercion to 'logical(1)'

The traceback is as follows:

> 11. FUN(X[[i]], ...)
> 10. lapply(X = X, FUN = FUN, ...)
> 9. sapply(node$children, function(x) {
> v <- GetAttribute(x, attribute, format = identity, ...)
> if (length(v) > 0 && !is.na(v))
> return(v) ...
> 8. Aggregate(node, attribute = "ids", aggFun = c)
> 7. fun(node, ...)
> 6. Do(t, fun, ...)
> 5. ARBOLtree$Do(function(node) node[["ids"]] <- Aggregate(node,
> attribute = "ids", aggFun = c), traversal = "post-order")
> 4. withCallingHandlers(expr, warning = function(w) if (inherits(w,
> classes)) tryInvokeRestart("muffleWarning"))
> 3. suppressWarnings({
> ARBOLtree$Do(function(node) node[["ids"]] <- Aggregate(node,
> attribute = "ids", aggFun = c), traversal = "post-order")
> ARBOLtree$Do(function(node) node[["samples"]] <- Aggregate(node, ...
> 2. propagateTree(divtree, srobj = srobj, categorical_attributes = categories,
> diversity_attributes = diversities, numerical_attributes = counts,
> total_attributes = totals)
> 1. ARBOLcentroidTaxonomy(seuobj.ds, categories = c("diagSub", "subset"),
> diversities = c("sample", "diagSub"), counts = c("diagSub",
> "subset"), tree_reduction = "pca", centroid_method = "mean",
> distance_method = "euclidean", hclust_method = "complete", ...

And the input code was:

> seuobj.ds <- ARBOLcentroidTaxonomy(
>   seuobj.ds,
>   categories = c("diagSub", "subset"),
>   diversities = c("sample", "diagSub"),
>   counts = c("diagSub", "subset"),
>   tree_reduction = "pca",
>   centroid_method = "mean",
>   distance_method = "euclidean",
>   hclust_method = "complete",
>   nboot = 100
> )

Where `seuobj.ds` is my Seurat object, "diagSub" is my disease classification, "subset" is the variable for cell types, and "sample" is the variable for individually-prepared samples.

Of note, this only seems to happen when I run ARBOL 4.0.0 in RStudio Server. When I use the same code to run ARBOL 3.0.0, which I have on my local machine, it completes without error

**Comment by MarcElosua** [comment]
I'm also getting the same error with ARBOL 4.0.0 and same traceback log. 

The lines that seem to be giving the error are in `propagateTree`:
```
suppressWarnings({
    ARBOLtree$Do(function(node) node[["ids"]] <- data.tree::Aggregate(node, 
        attribute = "ids", aggFun = c), traversal = "post-order")
    ARBOLtree$Do(function(node) node[["samples"]] <- data.tree::Aggregate(node, 
        attribute = "samples", aggFun = c), traversal = "post-order")
})
```
Here is the ARBOL object that is returning the error:
[ARBOLtree_debug.rds.zip](https://github.com/jo-m-lab/ARBOL/files/12588658/ARBOLtree_debug.rds.zip)

**Comment by kylekimler** [comment]
Hi Leonard and Marc, 
I believe the problem was coming from Matrix.utils package, which was used for "aggregate.Matrix" to run aggregations across clusters keeping within sparse Matrix notation for speed. I've now replaced the function with a custom aggregation function and removed Matrix.utils from ARBOL in the latest commit.
Thanks for the info!

**Comment by kylekimler** [comment]
This stems from a change in R 4.2: see
https://www.r-bloggers.com/2022/04/new-features-in-r-4-2-0/

logicals (if statements) used in dependencies that haven't been updated are deprecated.
data.tree::Aggregate contains such an if statement: 

```
Aggregate = function(node,
                     attribute,
                     aggFun,
                     ...) {

  if("cacheAttribute" %in% names(list(...))) stop("cacheAttribute not supported anymore! Please use Do instead.")

  if (isLeaf(node)) return ( GetAttribute(node, attribute, ...) )
  values <- sapply(node$children,
                   function(x) {
                     v <- GetAttribute(x, attribute, format = identity, ...)
                     if (length(v) > 0 && !is.na(v)) return(v)
                     Aggregate(x, attribute, aggFun, ...)
                   })
  result <- unname(aggFun(values))

  return (result)
}

```
I have replaced this function now with a copied version where i've changed the line with the logical - ARBOL.Aggregate

Give it a try now. looks to work again on my end.
